services:
  mongo:
    image: mongo
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  job-service:
    build: ../job-service
    image: job-service
    deploy:
      replicas: 3
    depends_on:
      - mongo
    environment:
      spring.data.mongodb.uri: "mongodb://job_user:job_password@mongo:27017/job"
  candidate-service:
    build: ../candidate-service
    image: candidate-service
    deploy:
      replicas: 3
    depends_on:
      - mongo
      - job-service
    environment:
      spring.data.mongodb.uri: "mongodb://candidate_user:candidate_password@mongo:27017/candidate"
  nginx:
    image: nginx
    depends_on:
      - job-service
      - candidate-service
    ports:
      - "80:80"
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"