services:
  mongo:
    image: mongo
#    profiles:
#      - db
    ports:
      - "27018:27017"
    volumes:
      - ./src/main/resources/data:/docker-entrypoint-initdb.d
  candidate-service:
    build: .
    image: candidate-service
    depends_on:
      - mongo
    profiles:
      - candidateApp
    ports:
      - "8081:8080"
    environment:
      spring.data.mongodb.uri: "mongodb://candidate_user:candidate_password@mongo:27017/candidate"


