services:
  mongo:
    image: mongo
#    profiles:
#      - db
    ports:
      - "27017:27017"
    volumes:
      - ./src/main/resources/data:/docker-entrypoint-initdb.d
  job-service:
    build: .
    image: job-service
    depends_on:
      - mongo
    profiles:
      - app
    ports:
      - "8080:8080"
    environment:
      spring.data.mongodb.uri: "mongodb://job_user:job_password@mongo:27017/job"